services:
  fastapi_app:
    build: .
    container_name: fastapi_app_v1
    ports:
      - "8080:8080"
    depends_on:
      - qdrant
    environment:
      - QDRANT_HOST=http://qdrant:6333

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_v1
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data_v1:/qdrant/storage

volumes:
  qdrant_data_v1:
    external: true